# Generated by Django 4.2.7 on 2023-11-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', 'created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updates',
            new_name='updated',
        ),
    ]
