# Generated by Django 4.2.7 on 2023-11-04 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_alter_message_created_alter_message_updates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='room',
            name='participations',
            field=models.ManyToManyField(blank=True, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
